

def useSnapshotDeps = (jmeVersionTag == 'SNAPSHOT')

dependencies {
    api project(':jme3-core')
    api(useSnapshotDeps ? libs.nostr4j.snapshot : libs.nostr4j)
    implementation(useSnapshotDeps ? libs.nge.platform.common.snapshot : libs.nge.platform.common)
    api(useSnapshotDeps ? libs.nge.platform.common.snapshot : libs.nge.platform.common)
    api project(':nge-core')
    api project(':nge-networking')
    api project(':nge-gui')
    api project(':nge-auth')
    api project(':nge-ads')

}

javadoc {
    // Disable doclint for JDK8+.
    if (JavaVersion.current().isJava8Compatible()){
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}
