

def useSnapshotDeps = (jmeVersionTag == 'SNAPSHOT')

ext.jmeNativeImageAdditionalTargetTypes = (
        (ext.has('jmeNativeImageAdditionalTargetTypes') ? ext.jmeNativeImageAdditionalTargetTypes : []) +
                ['org.ngengine.gui.nav.NavigatorInputHandler']
).unique()

dependencies {
    api project(':nge-core')
    implementation project(':nge-networking')
    implementation project(':jme3-core')
    implementation(useSnapshotDeps ? libs.nge.platform.common.snapshot : libs.nge.platform.common)
    testRuntimeOnly project(':jme3-plugins')
    testRuntimeOnly(useSnapshotDeps ? libs.nge.platform.jvm.snapshot : libs.nge.platform.jvm)
}

javadoc {
    // Disable doclint for JDK8+.
    if (JavaVersion.current().isJava8Compatible()){
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}
