

dependencies {
    api project(':nge-core')
    implementation project(':nge-networking')
    implementation project(':jme3-core')
    implementation "org.ngengine:nge-platform-common:${ngePlatformVersion}"
    testImplementation "org.ngengine:nge-platform-jvm:${ngePlatformVersion}"
}

javadoc {
    // Disable doclint for JDK8+.
    if (JavaVersion.current().isJava8Compatible()){
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}
