 
dependencies {
    api project(':nge-core')
    api project(':jme3-networking')
    testRuntimeOnly "org.ngengine:nge-platform-jvm:${ngePlatformVersion}"

}

configurations {
    testRuntimeClasspath {
        attributes {
            attribute(org.gradle.api.attributes.java.TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 21)
        }
    }
}

javadoc {
    // Disable doclint for JDK8+.
    if (JavaVersion.current().isJava8Compatible()){
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}
