 
def useSnapshotDeps = (jmeVersionTag == 'SNAPSHOT')

ext.jmeNativeImageAdditionalTargetTypes = (
        (ext.has('jmeNativeImageAdditionalTargetTypes') ? ext.jmeNativeImageAdditionalTargetTypes : []) +
                [
                        'org.ngengine.components.Component',
                        'org.ngengine.network.components.ActionMessage',
                        'org.ngengine.network.components.SnapshotMessage',
                        'org.ngengine.network.protocol.DiffableMessage'
                ]
).unique()

ext.jmeNativeImageAdditionalTargetAnnotations = (
        (ext.has('jmeNativeImageAdditionalTargetAnnotations') ? ext.jmeNativeImageAdditionalTargetAnnotations : []) +
                ['org.ngengine.network.protocol.NetworkSafe']
).unique()

dependencies {
    api project(':nge-core')
    api project(':jme3-networking')
    testRuntimeOnly(useSnapshotDeps ? libs.nge.platform.jvm.snapshot : libs.nge.platform.jvm)

}

configurations {
    testRuntimeClasspath {
        attributes {
            attribute(org.gradle.api.attributes.java.TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 21)
        }
    }
}

javadoc {
    // Disable doclint for JDK8+.
    if (JavaVersion.current().isJava8Compatible()){
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}
