

def useSnapshotDeps = (jmeVersionTag == 'SNAPSHOT')

ext.jmeNativeImageAdditionalTargetTypes = (
        (ext.has('jmeNativeImageAdditionalTargetTypes') ? ext.jmeNativeImageAdditionalTargetTypes : []) +
                ['org.ngengine.components.Component']
).unique()

dependencies {
    api project(':jme3-core')
    api(useSnapshotDeps ? libs.nostr4j.snapshot : libs.nostr4j)
    api(useSnapshotDeps ? libs.nge.platform.common.snapshot : libs.nge.platform.common)
    api libs.jakarta.annotation.api
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'

}

javadoc {
    // Disable doclint for JDK8+.
    if (JavaVersion.current().isJava8Compatible()){
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}
