sourceSets {
    main {
        java {
            srcDir 'src/ogre/java'
            srcDir 'src/gltf/java'
            srcDir 'src/fbx/java'
            srcDir 'src/xml/java'
        }
    }
}

def useSnapshotDeps = rootProject.ext.useSnapshotDependencies

dependencies {
    api project(':jme3-core')
    implementation "org.jmonkeyengine:drako:1.4.5-jme"
    implementation project(':jme3-plugins-json')
    implementation project(':jme3-plugins-json-gson')
    implementation(useSnapshotDeps ? libs.stb.image.snapshot : libs.stb.image)
    implementation(useSnapshotDeps ? libs.imagewebp.snapshot : libs.imagewebp)
    implementation(useSnapshotDeps ? libs.stb.truetype.snapshot : libs.stb.truetype)
    // jBasis currently has only a published snapshot, as required by this loader.
    implementation libs.basis.decoder.snapshot
    implementation(useSnapshotDeps ? libs.nanosvg.chicory.java.snapshot : libs.nanosvg.chicory.java) {
        exclude group: 'com.dylibso.chicory'
    }

    testRuntimeOnly project(':jme3-desktop')
    testRuntimeOnly project(':jme3-lwjgl3')
}
