/**
 * Copyright (c) 2025-2026, Nostr Game Engine
 * All rights reserved.
 */
package org.ngengine.web;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.StandardCharsets;
import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

/** Loads the reusable reflection metadata generated by the Native Image plugin. */
final class NgeReflectionMetadata {
    static final String CLASSES_RESOURCE = "META-INF/ngengine/reflection-classes.txt";
    static final String ROOTS_RESOURCE = "META-INF/ngengine/reflection-roots.txt";
    static final String METADATA_RESOURCE = "META-INF/ngengine/reflection-metadata.txt";

    private NgeReflectionMetadata() {
    }

    static Set<String> loadClasses(ClassLoader... classLoaders) {
        return load(CLASSES_RESOURCE, classLoaders);
    }

    static Set<String> loadRoots(ClassLoader... classLoaders) {
        return load(ROOTS_RESOURCE, classLoaders);
    }

    static Map<String, ReflectionProfile> loadProfiles(ClassLoader... classLoaders) {
        Map<String, ReflectionProfile> profiles = new LinkedHashMap<>();
        Set<ClassLoader> visited = java.util.Collections.newSetFromMap(
                new java.util.IdentityHashMap<ClassLoader, Boolean>());
        for (ClassLoader classLoader : classLoaders) {
            if (classLoader == null || !visited.add(classLoader)) {
                continue;
            }
            loadProfiles(classLoader, profiles);
        }
        return profiles;
    }

    private static Set<String> load(String resourceName, ClassLoader... classLoaders) {
        Set<String> classNames = new LinkedHashSet<>();
        Set<ClassLoader> visited = java.util.Collections.newSetFromMap(
                new java.util.IdentityHashMap<ClassLoader, Boolean>());
        for (ClassLoader classLoader : classLoaders) {
            if (classLoader == null || !visited.add(classLoader)) {
                continue;
            }
            load(classLoader, resourceName, classNames);
        }
        return classNames;
    }

    private static void load(
            ClassLoader classLoader,
            String resourceName,
            Set<String> classNames) {
        try {
            Enumeration<URL> resources = classLoader.getResources(resourceName);
            while (resources.hasMoreElements()) {
                URL resource = resources.nextElement();
                URLConnection connection = resource.openConnection();
                // Gradle can replace dependency JARs between consecutive TeaVM builds.
                // Avoid retaining a JarURLConnection to an obsolete archive.
                connection.setUseCaches(false);
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(
                        connection.getInputStream(), StandardCharsets.UTF_8))) {
                    String className;
                    while ((className = reader.readLine()) != null) {
                        className = className.trim();
                        if (!className.isEmpty() && !isJdkClass(className)) {
                            classNames.add(className);
                        }
                    }
                } catch (IOException exception) {
                    throw new IllegalStateException(
                            "Unable to read NGE reflection metadata at " + resource,
                            exception);
                }
            }
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to enumerate NGE reflection metadata", exception);
        }
    }

    private static void loadProfiles(
            ClassLoader classLoader,
            Map<String, ReflectionProfile> profiles) {
        try {
            Enumeration<URL> resources = classLoader.getResources(METADATA_RESOURCE);
            while (resources.hasMoreElements()) {
                URL resource = resources.nextElement();
                URLConnection connection = resource.openConnection();
                connection.setUseCaches(false);
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(
                        connection.getInputStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        mergeProfile(line, profiles);
                    }
                } catch (IOException exception) {
                    throw new IllegalStateException(
                            "Unable to read NGE reflection metadata at " + resource,
                            exception);
                }
            }
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to enumerate NGE reflection metadata", exception);
        }
    }

    private static void mergeProfile(
            String line,
            Map<String, ReflectionProfile> profiles) {
        String[] columns = line.split("\\t", -1);
        if (columns.length < 2) {
            return;
        }
        String className = columns[0].trim();
        if (className.isEmpty() || isJdkClass(className)) {
            return;
        }
        ReflectionProfile profile = profiles.computeIfAbsent(
                className, ignored -> new ReflectionProfile());
        String flags = columns[1];
        profile.declaredConstructors |= flags.indexOf('C') >= 0;
        profile.declaredFields |= flags.indexOf('F') >= 0;
        profile.declaredMethods |= flags.indexOf('D') >= 0;
        profile.publicMethods |= flags.indexOf('P') >= 0;
        profile.unsafeAllocated |= flags.indexOf('U') >= 0;
        if (columns.length >= 3 && !columns[2].isEmpty()) {
            for (String method : columns[2].split(";")) {
                if (!method.isEmpty()) {
                    profile.methods.add(method);
                }
            }
        }
    }

    private static boolean isJdkClass(String className) {
        return className.startsWith("java.")
                || className.startsWith("javax.")
                || className.startsWith("jdk.")
                || className.startsWith("sun.");
    }

    static final class ReflectionProfile {
        private boolean declaredConstructors;
        private boolean declaredFields;
        private boolean declaredMethods;
        private boolean publicMethods;
        private boolean unsafeAllocated;
        private final Set<String> methods = new LinkedHashSet<>();

        boolean hasDeclaredConstructors() {
            return declaredConstructors;
        }

        boolean hasDeclaredFields() {
            return declaredFields;
        }

        boolean hasDeclaredMethods() {
            return declaredMethods;
        }

        boolean hasPublicMethods() {
            return publicMethods;
        }

        boolean isUnsafeAllocated() {
            return unsafeAllocated;
        }

        boolean hasExplicitMethod(String signature) {
            return methods.contains(signature);
        }

        void merge(ReflectionProfile other) {
            declaredConstructors |= other.declaredConstructors;
            declaredFields |= other.declaredFields;
            declaredMethods |= other.declaredMethods;
            publicMethods |= other.publicMethods;
            unsafeAllocated |= other.unsafeAllocated;
            methods.addAll(other.methods);
        }
    }
}
