
apply plugin: 'java'

 
sourceSets {
    main {
        java {
            srcDir 'src/androidx-stubs/java'
        }
    }
}

def useSnapshotDeps = (jmeVersionTag == 'SNAPSHOT')

dependencies {
    compileOnly libs.androidx.annotation
    compileOnly libs.androidx.lifecycle.common
    compileOnly 'android:android'

    api project(':jme3-android')
    api project(':nge-app')
    api(useSnapshotDeps ? libs.nge.platform.common.snapshot : libs.nge.platform.common)
}


tasks.withType(Jar).configureEach {
    exclude('androidx/**')
}
