name: Integration tests

on:
  push:
  pull_request:

jobs:
  ScreenshotTests:
    name: "Run Screenshot Tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Mesa3D
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils libgl1-mesa-dri libgl1 libglx-mesa0 xvfb

      - name: Set environment variables for Mesa3D
        run: |
          echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV
          echo "MESA_LOADER_DRIVER_OVERRIDE=llvmpipe" >> $GITHUB_ENV

      - name: Start xvfb
        run: |
          sudo Xvfb :99 -ac -screen 0 1024x768x16 &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Verify Mesa3D Installation
        run: |
          glxinfo | grep "OpenGL"

      - name: Validate the Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Test with Gradle Wrapper
        run: |
          ./gradlew :jme3-screenshot-test:screenshotTest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: screenshot-test-report
          retention-days: 30
          path: |
            **/build/reports/**
            **/build/changed-images/**
            **/build/test-results/**